### ISSUE TITLE
提两条关于优化软件功能得建议。

### ISSUE THREAD

**Issue by Wanderknight3** [wgzeyu/GTASuperESC#1]
一：希望改进断网功能。不仅仅只是禁用网卡，而是单独禁用GTA5使用网络。
二：希望优化卡单人公开战局功能。现有的卡单人功能还不如ALT+ENTER窗口化右键来得方便，而且不稳定。建议升级为利用防火墙进出站规则设置的单人战局，附带白名单和公网IP查询功能更好。

**Comment by wgzeyu** [comment]
查了一下，这两个功能都能用netsh命令添加防火墙规则做到，下个版本应该会加上

**Comment by wgzeyu** [comment]
试试v5.6

**Comment by Wanderknight3** [comment]
> 试试v5.6


[CodeSwine.GTA5O.-.Private.Public.Lobby.V1.0.1.zip](https://github.com/wgzeyu/GTASuperESC/files/2479004/CodeSwine.GTA5O.-.Private.Public.Lobby.V1.0.1.zip)
卡单人已经完美支持了，附件是我作为参考的卡单软件。
但是对GTA.exe进程断网效果只是造成保存失败，并不会把玩家踢出任务或者直接拉到线下。也许GTA5相关联网进程不止这一个。
还是非常感谢你的工作，给玩家们无偿提供了很多便利，感谢！

**Comment by wgzeyu** [comment]
我卡分红试试

**Comment by wgzeyu** [comment]
卡分红没问题，飞机停好右下角第一个转圈消失瞬间按键进程断网，动画什么的都正常播放，
也显示任务成功，这时候左下角出现提示：保存失败，您的进度将在重新建立连接后被保存。 
结束后和队友一起进入了正常的公开战局，这时候退出游戏显示保存失败，是否确定退出，
退出之后再恢复网络，再打开游戏进入线上，分红还在，钱也拿到了。
看这提示感觉不重开游戏直接恢复进程网络应该不行

**Comment by Wanderknight3** [comment]
> 任务结束后进入公开战局的时候，左下角提示就从
> “保存失败，Rockstar云服务器现在不可用。您的进度将在重新建立连接后被保存。”
> 变成了
> “保存失败：无法连接Rockstar游戏服务。”
> 末日2准备任务还是挺不好打的。。你有没有别的任务试一下这个？

回头我会试试各种差事，有结果会回复你，学生党的时间不是很固定。
