### ISSUE TITLE
出站规则快捷键

### ISSUE THREAD

**Issue by KKKPJSKEY** [WGzeyu/GTASuperESC#12]
部分游戏内容需要断掉出站规则,希望作者添加下根据输入快捷键,对出站规则进行设置,以下是我cmd测试成功的指令
添加出站规则
`netsh advfirewall firewall add rule name=雷神加速器 dir=out action=block program=%SystemDrive%\Program_Files_(x86)\LeiGod_Acc\leigod.exe `
删除出站规则
`netsh advfirewall firewall delete rule name=雷神加速器 dir=out action=block program=%SystemDrive%\Program_Files_(x86)\LeiGod_Acc\leigod.exe `

**Comment by WGzeyu** [comment]
是指的进程断网的快捷键吗？

**Comment by WGzeyu** [comment]
如果是需要配置多个进程断网，直接在左下方修改设置就行，把进程断网的`GTA5.exe`改成`GTA5.exe,leigod.exe`

**Comment by WGzeyu** [comment]
另外，软件本身就支持恢复网络热键，右击快捷键输入框即可设置。
如果我没理解错的话，这个完全不需要更新软件，只需要修改设置就能实现。

**Comment by KKKPJSKEY** [comment]
哦原来如此，应该是的可以，进程断网可以断加速器的，感谢大佬指点
