### ISSUE TITLE
请问，这软件是不支持RadminLAN吗？

### ISSUE THREAD

**Issue by RUnknown** [WGzeyu/GTASuperESC#14]
这是个类似Hamachi的软件，但创建房间时没有走RadminLAN的网....创建房间时显示的还是本地地址，队友连不上...

**Comment by WGzeyu** [comment]
如果GTASuperESC没有正确识别IP地址，你可以输入端口号用手动创建，然后把给的内网房间号的ip改成RadminLAN的ip

**Comment by WGzeyu** [comment]
端口号随便填一个就行，我记得不填也行（好像会随机生成）

**Comment by RUnknown** [comment]
谢谢！刚刚跟朋友试了，原来房间号的ip可以不是那个ip啊....

**Comment by WGzeyu** [comment]
> 谢谢！刚刚跟朋友试了，原来房间号的ip可以不是那个ip啊....

当然可以不是，如果不需要让用户改，那就直接提供新版房间号了
新版房间号是这种格式：`jtkLiUZHatnLbDuZsEx+RfCwtksu0hws` 还能支持纠错识别
提供旧版房间号就是为了能自己改，输出信息里也写了`房间号=地址:端口-xxxx(随机的密码)`
IP地址改成域名也行，但不能含有`-`等字符(否则可能导致密码识别错误)
