### ISSUE TITLE
希望能增加对ipv6的支持

### ISSUE THREAD

**Issue by LemonYdd** [WGzeyu/GTASuperESC#15]
因为ipv4公网基本很难申请了，但是ipv6公网地址基本都有，所以希望大大能增加ipv6的支持

**Comment by WGzeyu** [comment]
这个是个很老的项目了，当时写的也比较烂，支持ipv6几乎得重写一个新的，更何况其实就算ipv4也有更好的实现方式，可以udp打洞之类的，如果真的想重新做一个可能会一起考虑支持，但是目前没兴趣折腾这个...
其实也不一定非得公网，目前可以用Hamachi、RadminLAN之类的软件创建虚拟内网，走内网联机，或者通过内网穿透来联机，或者直接用一键创建来联机，啥都不用配置。
