### ISSUE TITLE
不会使用GitHub反馈问题的进！贴吧原地址被系统删除，可在新帖里回帖反馈

### ISSUE THREAD

**Issue by wgzeyu** [wgzeyu/GTASuperESC#2]
### 新帖地址：[https://tieba.baidu.com/p/6233093902](https://tieba.baidu.com/p/6233093902)

**Comment by Dongyang7** [comment]
谢谢分享，我刚刚尝试在Google搜索了半天没搜到你这个软件，后来发现因为你是gtasuperesc，整体是一个字符串，而我搜的“gta super esc", Google识别不出来。。。

**Comment by SkyJin0426** [comment]
感谢分享

**Comment by ZZHLMY** [comment]
谢谢你的软件，很好用，但是有个问题，自从我用了软件之后，用雷神加速器连接服务器老是连接失败，不懂是什么问题，请问楼主能说下是什么问题吗？

**Comment by wgzeyu** [comment]
> 谢谢你的软件，很好用，但是有个问题，自从我用了软件之后，用雷神加速器连接服务器老是连接失败，不懂是什么问题，请问楼主能说下是什么问题吗？

如果你没专门设置过断雷神加速器的网的话，那就和软件无关。

**Comment by KousakaYuuji** [comment]
你好大佬，软件很实用。贴吧帖子没了所以在这里发一下。

最近我在用家里的另一台电脑做实验，两台电脑公网ip一样端口不一样（游戏内查看），其中一台电脑开锁单人战局，另一台却无法加入。因为公网ip一样所以加不加白名单并没区别，看了下创建的两条规则里都是针对6672端口。请问这种情况下如何更改规则来实现锁双人战局呢？谢谢~

**Comment by ZZHLMY** [comment]
> > 谢谢你的软件，很好用，但是有个问题，自从我用了软件之后，用雷神加速器连接服务器老是连接失败，不懂是什么问题，请问楼主能说下是什么问题吗？
> 
> 如果你没专门设置过断雷神加速器的网的话，那就和软件无关。

好的
