### ISSUE TITLE
服务器问题

### ISSUE THREAD

**Issue by Bywnb** [wgzeyu/GTASuperESC#3]
您好，您提供了PHP源码，我想用此源码连接自己的服务器而不是连接您的服务器，我目前只用宝塔部署了PHP源码，请问是否要开放端口以及软件如何对接和服务器环境等

**Comment by wgzeyu** [comment]
https://github.com/wgzeyu/workerman-chat/releases 
运行这个源码需要直接在服务器上执行命令，切换到相应目录后php ./start.php即可，不支持在空间中运行。
举例说明这套php源码的话，就相当于一套exe程序一样，只是他是用php写的。
你无法在网站服务器里运行，需要直接执行单独运行。
具体的程序设置，在Applications/Chat目录中，如果有用不到的功能可以直接删掉对应的配置文件。

**Comment by wgzeyu** [comment]
关于这套框架的文档以及如何启动/停止运行，可以看这个：
http://doc2.workerman.net/start-and-stop.html

**Comment by Bywnb** [comment]
方便留一下QQ交流一下吗？这里交流效率不太高

**Comment by wgzeyu** [comment]
其实如果我们都在线的话这里交流实际上是可以实时更新的，不需要刷新页面，QQ交流也可以。你QQ多少？
