### ISSUE TITLE
UTF-8乱码问题

### ISSUE THREAD

**Issue by howxcheng** [wgzeyu/GTASuperESC#4]
系统使用utf-8编码会整个乱码
![image](https://user-images.githubusercontent.com/47664542/76581684-3ff29a00-650f-11ea-92d3-55dd0a598f0c.png)
![image](https://user-images.githubusercontent.com/47664542/76581776-81834500-650f-11ea-9ce5-3e58d1c3d161.png)

**Comment by wgzeyu** [comment]
暂时无法解决，毕竟易语言不支持Unicode，建议关闭UTF-8选项，或者切换为英语。

**Comment by howxcheng** [comment]
好的
