### ISSUE TITLE
关于自动创建房间的问题

### ISSUE THREAD

**Issue by DoveKingWang** [wgzeyu/GTASuperESC#5]
大佬。自己创建房间的话，有无支持自建服务器的方法？大陆的公网ip属实是难搞

**Comment by wgzeyu** [comment]
联通电信打个客服就能申请公网IP，不算难搞。除非你网络设置有问题，并且你不会设。
记得在自动创建失败的提示里面我放过用内网穿透手动创建房间（本机服务器）的教程
