### ISSUE TITLE
进程断网后恢复无反应

### ISSUE THREAD

**Issue by swhoro** [wgzeyu/GTASuperESC#8]
参考某一b站视频：https://www.bilibili.com/video/av90901404
尝试断网卡分红
使用“进程断网”卡出分红后进大厅，再点软件的恢复，左下角依然显示“保存失败：无法连接rockstar游戏服务”
但是回复之后可以正常接到莱斯特信息、开分红、组队并完成任务，但是无法从设施中取得零食、进准备时无法购买护甲
左下角标志一直在，直到做完分红后获取奖励、进入另一战局才没有左下角标志
未使用加速器，在路由器上挂了魔法

**Comment by wgzeyu** [comment]
从描述来看，软件功能应该是正常的，可能是游戏的问题。
